name: "List modules"
description: 'List all the active modules for a Maven project.'
inputs:
  path:
    description: 'Path to the Maven project.'
    required: false
    default: '.'
outputs:
  modules:
    description: "List of all active modules."
    value: ${{ steps.list.outputs.modules }}
runs:
  using: "composite"
  steps:
    - id: list
      env:
        JAVA_HOME: /usr/lib/jvm/jdk1.8.0_301/
      run: |
        MODULES=$(mvn -f ${{ inputs.path }} -Dexec.executable='echo' -Dexec.args='${project.groupId}:${project.artifactId}' exec:exec -q | \
        jq  --raw-input .  | \
        jq --slurp -c .)
        echo "::set-output name=modules::$MODULES"
      shell: bash