name: Publish artifacts to the Maven Repository
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: self-hosted
    env:
      JAVA_HOME: /usr/lib/jvm/jdk1.8.0_301/
    steps:
      - uses: actions/checkout@v3
      - name: deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_KEY_PASSPHRASE: ${{ secrets.DEPLOY_KEY_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: bash .github/deployment/deploy.sh