name: Scan a maven project
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository for the maven project.'
        required: true
        type: string
jobs:
  scan:
    runs-on: self-hosted
    timeout-minutes: 2880
    steps:
      - name: Checkout Pomelo
        uses: actions/checkout@v3
        with:
          path: pomelo
      - name: Build Pomelo
        uses: ./pomelo/.github/actions/build
        with:
          project: pomelo
          skip_tests: true
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          path: project
      - name: Scan project
        env:
          JAVA_HOME: /usr/lib/jvm/jdk1.8.0_301/
          REPORT: pomelo/pomelo-scan.txt
          POMELO_EXTENSION_JAR: pomelo/pomelo-maven-lifecycle/target/pomelo-maven-lifecycle-1.0.0-SNAPSHOT.jar
          MAVEN_OPTS: >
            -Dhttps.protocols=TLSv1.2 -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true
            -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
            -DinstallAtEnd=true
          MAVEN_CLI_OPTS: --batch-mode --errors --fail-never --show-version
        run: |
          mvn -f project -Dmaven.ext.class.path=$POMELO_EXTENSION_JAR -Dpomelo.phase=scan -Dpomelo.scan.report=$REPORT $MAVEN_CLI_OPTS install
          cat $REPORT
        shell: bash
