name: Scan project
on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'GitHub repository for the Maven project to be scanned.'
        required: true
        type: string
      timeout:
        description: "Amount of time in seconds after which forked test processes should be killed or 0 if test processes should 
        never be timed out."
        required: false
        type: string
        default: "1800"
jobs:
  generate-matrix:
    runs-on: self-hosted
    steps:
      - name: Checkout Pomelo
        uses: actions/checkout@v3
        with:
          path: pomelo
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.repository }}
          path: project
      - name: List modules
        id: list-modules
        uses: ./pomelo/.github/actions/list-modules
        with:
          path: ./project
      - name: Create report directory
        run: |
          mkdir -p /ci-logs/public/katie/pomelo/scan/${{ github.run_id }}/
        shell: bash
    outputs:
      modules: ${{ steps.list-modules.outputs.modules }}
  scan-modules:
    runs-on: self-hosted
    timeout-minutes: 10
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.generate-matrix.outputs.modules) }}
    steps:
      - name: Checkout Pomelo
        uses: actions/checkout@v3
        with:
          path: pomelo
      - name: Scan ${{ github.event.inputs.repository }} ${{ matrix.module }}
        env:
          REPORT_FILE: /ci-logs/public/katie/pomelo/scan/${{ github.run_id }}/${{ strategy.job-index  }}.csv
        uses: ./pomelo/.github/actions/scan
        with:
          path: project
          repository: ${{ github.event.inputs.repository }}
          module: ${{ matrix.module }}
          timeout: ${{ github.event.inputs.timeout }}
          report: $REPORT_FILE
      - name: Print scan report
        env:
          REPORT_FILE: /ci-logs/public/katie/pomelo/scan/${{ github.run_id }}/${{ strategy.job-index  }}.csv
          REPORT_LOCATION: public/katie/pomelo/scan/${{ github.run_id }}/${{ strategy.job-index  }}.csv
        run: |
          cat $REPORT_FILE
          echo "Report saved to: https://ci.in.ripley.cloud/logs/$REPORT_LOCATION"
        shell: bash
  create-report:
    runs-on: self-hosted
    if: always()
    needs: scan-modules
    steps:
      - name: Print scan report
        env:
          REPORT_DIR: /ci-logs/public/katie/pomelo/scan/${{ github.run_id }}
        run: |
          cd "$REPORT_DIR"
          HEADER="project_id,plugin_name,execution_id,test_class_name,test_method_name,runner_class_name,"
          HEADER+="unambiguous,original_result,isolated_result,generators_status"
          echo $HEADER > report.csv
          tail -n+2 -q *.csv >> report.csv
          cat report.csv
        shell: bash