name: Run tests
on: [ push, pull_request ]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        uses: ./.github/actions/build
        with:
          skip_tests: false
      - name: Scan examples
        run: |
          mvn -f pomelo-examples install -Dpomelo.phase=scan -Dpomelo.scan.report=pomelo-scan.csv
          cat pomelo-scan.csv
        shell: bash
